name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: SFTP uploader
      uses: wangyucode/sftp-upload-action@v2.0.4
      with:
        host: ${{ secrets.SFTP_HOST }}
        password: ${{ secrets.SFTP_PASSWORD }}
        localDir: "dist"
        remoteDir: ${{ secrets.SFTP_DIR }}